- name: Converge
  vars_files:
    - testing_vars.yaml
  hosts: all
  tasks:
    - name: "Include Common Role"
      include_role:
        name: "common"
    - name: "Include PowerDNS Role"
      include_role:
        name: "powerdns_role"
